In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("results_0_50.csv")
df

    id                                           response
0    0  Okay, let's tackle part a first. So, we need t...
1    1  Okay, let's try to figure out this problem. So...
2    2  Okay, let's tackle this problem step by step. ...
3    3  Okay, let's try to figure out this problem ste...
4    4  Okay, let's see. The problem says that the poi...
5    5  Okay, let's tackle this ANOVA problem step by ...
6    6  Okay, let's see. So, the problem is about find...
7    7  This is a complex or challenging question, and...
8    8  Okay, let's try to figure out this problem. So...
9    9  Okay, let's see. I need to solve the equation ...
10  10  Okay, let's try to figure out this integral. T...
11  11  Okay, let's try to tackle this problem step by...
12  12  Okay, let's tackle part (a) first. So, we have...
13  13  Okay, let's try to solve this integral: ∫ 6 / ...
14  14  Okay, let's see. I need to solve the equation ...
15  15  Okay, let's tackle this problem step by step. ...
16  16  This is a complex or challenging question, and...
17  17  Okay, let's try to solve this problem step by ...
18  18  Okay, let's try to figure out this problem. So...
19  19  Okay, let's try to tackle this problem step by...
20  20  Okay, let's tackle this problem step by step. ...
21  21  Okay, let's tackle part (a) first. We need to ...
22  22  Okay, let's try to solve this problem step by ...
23  23  Okay, let's try to figure out this problem ste...
24  24  Okay, let's see. I need to find the sum of the...
25  25  Okay, let's tackle part (a) first: the relativ...
26  26  Okay, let's try to solve this problem step by ...
27  27  Okay, let's tackle these two trigonometric equ...
28  28  Okay, let's tackle each part one by one. \n\nS...
29  29  Okay, let's try to solve this problem step by ...
30  30  Okay, let's tackle this problem step by step. ...
31  31  Okay, let's tackle these two division problems...
32  32  Okay, let's tackle this problem step by step. ...
33  33  Okay, let's try to solve this problem step by ...
34  34  Okay, let's try to figure out this problem ste...
35  35  Okay, let's try to figure out this problem. So...
36  36  Okay, let's see. I need to multiply these two ...
37  37  Okay, let's try to solve this problem step by ...
38  38  Okay, let's try to figure out this integral pr...
39  39  Okay, let's see. The problem says one piece of...
40  40  Okay, let's see. The problem is about a homing...
41  41  This is a complex or challenging question, and...
42  42  Okay, let's tackle these questions one by one....
43  43  Okay, let's try to figure out how to express \...
44  44  Okay, let's tackle each part one by one. I nee...
45  45  Okay, let's try to figure this out. So the pro...
46  46  Okay, let's tackle this problem step by step. ...
47  47  Okay, let's try to solve this problem: Find al...
48  48  Okay, let's see. I need to rewrite the exponen...
49  49  Okay, let's try to figure out how to find β, t...

In [3]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_50_85.csv")]), columns = ['id', 'response'])
df

    id                                           response
0    0  Okay, let's tackle part a first. So, we need t...
1    1  Okay, let's try to figure out this problem. So...
2    2  Okay, let's tackle this problem step by step. ...
3    3  Okay, let's try to figure out this problem ste...
4    4  Okay, let's see. The problem says that the poi...
..  ..                                                ...
80  80  Okay, let's try to simplify this fraction by r...
81  81  Okay, let's see. I need to find the average te...
82  82  Okay, let's tackle this problem step by step. ...
83  83  This is a complex or challenging question, and...
84  84  Okay, let's see. I need to subtract these inte...

[85 rows x 2 columns]

In [4]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_85_125.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
120  120  This is a complex or challenging question, and...
121  121  Okay, let's see. So Fabrienne needs a total of...
122  122  Okay, let's tackle these two questions one by ...
123  123  Okay, let's try to figure out this problem. So...
124  124  Okay, let's try to figure out this problem ste...

[125 rows x 2 columns]

In [5]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_125_160.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
155  155  Okay, let's try to figure out this problem. So...
156  156  Okay, let's try to figure out the eigenvalues ...
157  157  Okay, let's try to solve this problem step by ...
158  158  Okay, let's tackle these two questions one by ...
159  159  Okay, let's see. I need to change these percen...

[160 rows x 2 columns]

In [6]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_160_200.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
195  195  Okay, let's try to figure out this confidence ...
196  196  Okay, let's see. I need to solve this right tr...
197  197  Okay, let's try to figure out this problem. So...
198  198  This is a complex or challenging question, and...
199  199  This is a complex or challenging question, and...

[200 rows x 2 columns]

In [7]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_200_250.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
245  245  Okay, let's see. The problem is about Lily's w...
246  246  Okay, let's tackle these division problems one...
247  247  Okay, let's try to solve this problem step by ...
248  248  This is a complex or challenging question, and...
249  249  Okay, let's see. I need to approximate the fou...

[250 rows x 2 columns]

In [8]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_250_300.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
295  295  Okay, let's try to solve this problem step by ...
296  296  Okay, let's try to solve this problem step by ...
297  297  Okay, let's tackle this hypothesis testing pro...
298  298  Okay, let's try to figure out this problem ste...
299  299  Okay, let's tackle part a first. The problem s...

[300 rows x 2 columns]

In [9]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_300_350.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
345  345  Okay, let's see. I need to find all real zeros...
346  346  Okay, let's see. I need to write these divisio...
347  347  Okay, let's try to tackle this problem step by...
348  348  Okay, let's try to solve this integral: ∫ [arc...
349  349  Okay, let's see. I need to subtract 4/9 from 1...

[350 rows x 2 columns]

In [10]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_350_400.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
395  395  Okay, let's tackle this problem step by step. ...
396  396  Okay, let's tackle these interval notation pro...
397  397  Okay, let's see. The problem is about a crysta...
398  398  Okay, let's try to figure out this problem ste...
399  399  Okay, let's try to tackle this problem step by...

[400 rows x 2 columns]

In [11]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_400_450.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
445  445  Okay, let's try to figure out this probability...
446  446  Okay, let's see. I need to find the standard e...
447  447  Okay, let's see. I need to solve this compound...
448  448  Okay, let's see. The question is whether the f...
449  449  Okay, let's try to work through this problem s...

[450 rows x 2 columns]

In [12]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_450_485.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
480  480  Okay, let's tackle this problem step by step. ...
481  481  Okay, let's try to figure out this problem ste...
482  482  Okay, let's try to solve this problem. So, we ...
483  483  Okay, let's try to tackle this problem step by...
484  484  Okay, let's try to solve this problem step by ...

[485 rows x 2 columns]

In [13]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_485_525.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
520  520  Okay, let's see. So I need to figure out how m...
521  521  Okay, let's see. The problem says two numbers ...
522  522  Okay, so I need to solve the equation cos(x) =...
523  523  This is a complex or challenging question, and...
524  524  Okay, let's try to figure out the Dini derivat...

[525 rows x 2 columns]

In [14]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_525_560.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
555  555  Okay, let's tackle part (a) first. So we need ...
556  556  Okay, let's try to figure out this problem ste...
557  557  Okay, let's see. The problem is to find the ab...
558  558  Okay, let's see. I need to find a linear funct...
559  559  Okay, let's see. I need to multiply -8 and 3/4...

[560 rows x 2 columns]

In [15]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_560_600.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
595  595  Okay, let's tackle part a first. So, we're dea...
596  596  Okay, let's try to figure out this problem. So...
597  597  This is a complex or challenging question, and...
598  598  Okay, let's try to figure out this problem. So...
599  599  Okay, let's see. I need to find the standard e...

[600 rows x 2 columns]

In [16]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_600_650.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
645  645  Okay, let's see. I need to express profit, P, ...
646  646  Okay, let's try to figure out this problem ste...
647  647  Okay, let's try to figure this out. So the pro...
648  648  Okay, let's try to figure out this problem ste...
649  649  This is a complex or challenging question, and...

[650 rows x 2 columns]

In [17]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_650_700.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
695  695  Okay, let's try to figure out the order of the...
696  696  Okay, let's see. I need to complete the square...
697  697  Okay, let's see. The problem says that r varie...
698  698  Okay, let's see. The problem says that 76 time...
699  699  Okay, let's try to solve this problem step by ...

[700 rows x 2 columns]

In [18]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_700_750.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
745  745  Okay, let's tackle these trigonometric identit...
746  746  Okay, let's tackle each problem one by one. I ...
747  747  Okay, let's see. I need to encrypt P=24 using ...
748  748  Okay, let's tackle this problem step by step. ...
749  749  Okay, let's tackle this problem step by step. ...

[750 rows x 2 columns]

In [19]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_750_800.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
795  795  Okay, let's try to figure out this problem ste...
796  796  This is a complex or challenging question, and...
797  797  Okay, let's try to solve this problem step by ...
798  798  Okay, let's try to solve this equation: √(t - ...
799  799  This is a complex or challenging question, and...

[800 rows x 2 columns]

In [20]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_800_850.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
845  845  Okay, let's see. I need to solve this problem:...
846  846  Okay, let's tackle these ceiling function prob...
847  847  Okay, let's try to solve this problem step by ...
848  848  Okay, let's try to solve this problem. We need...
849  849  Okay, let's see. I need to find the closed for...

[850 rows x 2 columns]

In [21]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_850_900.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
895  895  Okay, let's see. I need to find an exponential...
896  896  Okay, let's tackle each question one by one. I...
897  897  Okay, let's try to figure out this problem ste...
898  898  Okay, let's see. I need to simplify the expres...
899  899  Okay, let's try to compute this integral: ∫ [t...

[900 rows x 2 columns]

In [22]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_900_922.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
917  917  Okay, let's tackle part a first. So, we need t...
918  918  Okay, let's try to figure out the spectral rad...
919  919  This is a complex or challenging question, and...
920  920  Okay, let's try to figure out how many 2s we'l...
921  921  Okay, let's try to find the zeros of this func...

[922 rows x 2 columns]

In [23]:
df = pd.DataFrame(np.vstack([df, pd.read_csv("results_922_943.csv")]), columns = ['id', 'response'])
df

      id                                           response
0      0  Okay, let's tackle part a first. So, we need t...
1      1  Okay, let's try to figure out this problem. So...
2      2  Okay, let's tackle this problem step by step. ...
3      3  Okay, let's try to figure out this problem ste...
4      4  Okay, let's see. The problem says that the poi...
..   ...                                                ...
938  938  Okay, let's see. Penelope is paying a dinner b...
939  939  Okay, let's try to solve this problem step by ...
940  940  Okay, let's try to figure this out step by ste...
941  941  Okay, let's tackle this step by step. I need t...
942  942  Okay, let's try to solve this equation: 5 time...

[943 rows x 2 columns]

In [24]:
df.to_csv('result.csv', index = False)